# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2GoImcJ7RIVzZhyUt8GHuG2aPiHjj2B
"""

# Insertion Sort in Monotonically Decreasing Order

def insertion_sort_desc(arr):
    # Traverse from the second element to the end
    for j in range(1, len(arr)):
        key = arr[j]
        i = j - 1

        # Move elements that are smaller than key
        # to one position ahead
        while i >= 0 and arr[i] < key:
            arr[i + 1] = arr[i]
            i -= 1

        arr[i + 1] = key

    return arr


# Example array
array = [12, 5, 8, 19, 1, 25, 7]

print("Original Array:")
print(array)

sorted_array = insertion_sort_desc(array)

print("\nSorted Array in Monotonically Decreasing Order:")
print(sorted_array)